{{- if .Values.pdb.enabled }}
{{- range $key, $svc := .Values.services }}
{{- if gt (int $svc.replicas) 1 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  labels:
    {{- include "recast.serviceLabels" (dict "Chart" $.Chart "Release" $.Release "component" $svc.name) | nindent 4 }}
spec:
  minAvailable: {{ $.Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "recast.serviceSelector" (dict "Release" $.Release "component" $svc.name) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
